- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt update

  - name : Install Docker
    command : sudo apt install docker.io -y

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd -p 8084:8081 vikash9755/financeme:1.0
